CXX = g++

CXXFLAGS = -Wall -Werror -pedantic --std=c++11 -g

1test.exe: 1test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

2test.exe: 2test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

3test.exe: 3test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

4test.exe: 4test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

5test.exe: 5test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

6test.exe: 6test.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

7misctest.exe: 7misctest.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

.SUFFIXES:

.PHONY: clean